SELECT  [TIUTemplateSID]
      ,[TIUTemplateIEN]
      ,[Sta3n]
      ,[TemplateName]
     
      ,[TemplateInactiveFlag]
      ,[ExcludeFlag]
      ,[TemplateStaffSID]
      ,[UserClassSID]
      ,[DialogFlag]
      ,[DisplayFlag]
      ,[FirstLineFlag]
      ,[OneItemFlag]
      ,[HideDialogItemsFlag]
      ,[HideTreeItemsFlag]
      ,[IndentItemsFlag]
      ,[ReminderDialogSID]
      ,[CopyLockFlag]
      ,[ConsultLockFlag]
      ,[ParentFileNumber]
      ,[RequestServiceSID]
      ,[GMRCProcedureSID]
      ,[TIUDocumentDefinitionSID]
  FROM [LSV].[Dim].[TIUTemplate]
  Where Sta3n=612
  AND Templatename LIKE ('%WELLNESS%')
